---
title: Talk
author:
- Carter Allen
- Brian Neelon
- Sara E. Benjamin-Neelon
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Introduction: Infant Motor Development

- Infant motor development has been shown to be an important predictor of health later in life.

- Early motor development has been associated with improved physical activity, cognitive function, and educational attainment. 

- Delayed motor development has been linked to congnitive disorders in adulthood.

- __Interest lies in identifying factors related to differing developmental patterns.__

# Nurture Study

- Birth cohort of predominantly black women and their infants residing in the southeastern U.S. between 2013 and 2017

- Infant development was assessed quarterly through the first year of life at 3, 6, 9, and 12 months of age.

- __Bayley composite score__ was used to measure infant development. Scores range from 40 to 160, with higher scores indicating more advanced development.

- __Food security__ was assessed during pregnancy and infancy. It was hypothesized that _lack of food security during pregnancy contributes to slower motor development during infancy_.

# Statistical Challenges

- Standard repeated measures models of Bayley scores in the Nurture data feature __skewed residuals__.

- Bayley scores exhibit __intermittent missingness__, with approximately one third of Bayley scores missing at each timepoint. 

- Bayley scores are correlated through time in an __unstructured manner__.

- Existing approaches to modeling development clusters fail to account for one of more of these relevant features of the Nurture data.

# Model: Mixture Model

We propose a finite mixture model that accommodates skewness in residuals, non-ignorable missingness in outcomes, and unstructured dependence among repeated measures.

The model is based on the multivariate skew normal (MSN) distribution, with extensions to the multivariate skew-$t$ (MST) distribution.

Specifically, let $\mathbf{y}_{i}=(y_{i1},\ldots,y_{iJ})^T$ be a $J \times 1$ vector of standardized Bayley scores for subject $i\;(i=1,\ldots,n)$. We propose a mixture model of the form
\begin{equation}
	\label{eq:mixture}
f(\mathbf{y}_i) = \sum_{k = 1}^{K} \pi_{ki} f(\mathbf{y}_i|\boldsymbol\theta_k),
\end{equation}
where $\boldsymbol\theta_k$ is the set of parameters specific to cluster $k$ ($k = 1,...,K$) and $\pi_{ki}$ is a subject-specific mixing weight representing the probability that subject $i$ belongs to cluster $k$.

# Model: MSN Components

For posterior inference, we introduce a latent cluster indicator variable $z_i$ taking the value $k \in \{1,...,K\}$ with probability $\pi_{ki}$. Given $z_i = k$, we assume $\mathbf{y}_{i}$ is distributed according to a $J$-dimensional multivariate skew normal (MSN) density:
\begin{equation}
\mathbf{y}_{i}|(z_i=k) &\stackrel{ind}{\sim}& \text{MSN}_J(\boldsymbol\zeta_{ki},\boldsymbol\alpha_k,\boldsymbol\Omega_k), ~\text{with density} \label{eq:msndens}\nonumber
\end{equation}